FROM postgres:18.6-bookworm
WORKDIR /migrations
COPY supabase/migrations ./sql
COPY tools/migrate.sh ./migrate.sh
RUN chmod 0555 ./migrate.sh && chown -R postgres:postgres /migrations
USER postgres
ENTRYPOINT ["/migrations/migrate.sh"]
